### ISSUE TITLE
inspire theme doesnt have topConcept

### ISSUE THREAD

**Issue by landryb** [geonetwork/util-gemet#1]
I see TopConcept were added to gemet thesaurus in https://github.com/geonetwork/util-gemet/commit/7bbfbed04439aef157f5a66d251eeced5f2f7309, but if i try to import inspire-theme.rdf from this repo in GN3 opening the editor page complains that this thesaurus doesn't have top concepts.
`srv/fre/thesaurus.topconcept?_content_type=json&thesaurus=external.theme.inspire-theme` is called, and that returns a 500 code with:

```
         "id": "error",
        "class": "TermNotFoundException",
        "service": "thesaurus.topconcept",
        "message": "No top concepts/keywords in file /data/webapps/geonetwork/config/codelist/external/thesauri/theme/inspire-theme.rdf",
```

@fxprunayre any idea ? Is it an issue in geonetwork handling of thesaurus without topconcepts, or those should be added to inspire-theme.rdf too ?

**Comment by fxprunayre** [comment]
If there is no top concept, then the editor should fallback with default keyword picker. Can you still choose keyword from the thesaurus ?

**Comment by landryb** [comment]
Yes, you can still choose the keyword from the thesaurus, it's just that the 500 error code + 30 lines of traceback in the logfile is just ugly - the exception should be gracefully handled/logged as info/debug ? Now that i've tested adding keywords from both 'gemet concepts' and 'inspire themes' i see the UI differences in behaviour between thesaurus with and without topconcepts.

**Comment by fxprunayre** [comment]
Fixed in https://github.com/geonetwork/core-geonetwork/commit/3f419e3fa2aca00f348b7c355659ce15e64c3b0c

**Comment by landryb** [comment]
worth backporting to 3.0.x ?

**Comment by etj** [comment]
I guess that fixes should be backported to stable branches.

**Comment by archaeogeek** [comment]
I'm still seeing this error in 3.0.5, so a big +1 for it being backported to the 3.0.x branch
